config/routes.rb
Rails.application.routes.draw do
  root 'web_app#landing'
  resources :projects do
    resources :donations
  end
  
  # oAuth
  get '/auth/:provider/callback' => 'sessions#omniauth'
  delete '/logout' => 'sessions#destroy'
  
  # Default to home
  get '*all', to: 'web_app#landing', constraints: lambda { |req|
    req.path.exclude? 'rails/active_storage'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  has_many_attached :images
  has_many :donations
  belongs_to :owner, foreign_key: 'project_owner_id', class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects, foreign_key: 'project_owner_id'
  has_many :donations
  
  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_initialize do |user|
      user.user_name = auth.info.name
      user.email = auth.info.email
      user.password = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/donations_controller.rb
class DonationsController < WebAppController
  before_action :get_project

  def create
    sleep 5 # To simulate a real transaction
    @donation = @project.donations.new(donation_params)
    @donation.user = current_user if logged_in? # Otherwise it will be an anonymous donation
    respond_to do |format|
      if @donation.save
        format.json { render json: {donation: @donation, user: current_user, current_amount: @project.donations.sum(:amount)} }
      else
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end
  
  private
  def get_project
    @project = Project.find(params[:project_id])
  end
  def donation_params
    params.require(:donation).permit(:amount, :payment_method, :project_id, :transaction_status)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < WebAppController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_cover_img, only: [:index, :show, :new, :edit]
  
  before_action :require_login, only: [:index, :new, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.owner = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cover_img
      @cover_img = (@project && @project.images.attached?) ? url_for(@project.images.first) : ActionController::Base.helpers.asset_path('dr1.jpg')
      @vh = 30
    end
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :beneficiary, :description, :goal_amount, :goal_deadline, :project_status)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def omniauth
    @user = User.from_omniauth(auth)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private
  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/web_app_controller.rb
class WebAppController < ActionController::Base
  # Include Login methods
  include WebAppHelper
  layout 'application'
  def landing
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/web_app_helper.rb
module WebAppHelper
  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    !!session[:user_id]
  end

  def require_login
    unless logged_in?
      redirect_to root_path, alert: "You must be logged in to access this section"
    end
  end
end

module ActionView
  module Helpers
    class FormBuilder 
      def date_select(method, options = {}, html_options = {})
        existing_date = @object.send(method) 
        formatted_date = existing_date.to_date.strftime("%F") if existing_date.present?
        text_field(method, :value => formatted_date, :class => "form-control datepicker", :"data-date-format" => "YYYY-MM-DD")
      end

      # Not needed yet, but left here as a snippet.
      def datetime_select(method, options = {}, html_options = {})
        existing_time = @object.send(method) 
        formatted_time = existing_time.to_time.strftime("%F %I:%M %p") if existing_time.present?
        @template.content_tag(:div, :class => "input-group") do    
          text_field(method, :value => formatted_time, :class => "form-control datetimepicker", :"data-date-format" => "YYYY-MM-DD hh:mm A") +
          @template.content_tag(:span, @template.content_tag(:span, "", :class => "glyphicon glyphicon-calendar") ,:class => "input-group-addon")
        end
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>#FightBackTheCovid</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0, name="viewport" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <!-- Fonts and icons -->
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
    
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-color-on-scroll navbar-transparent fixed-top navbar-expand-lg"  color-on-scroll="100">
      <div class="container">
        <div class="navbar-translate">
          <a class="navbar-brand" href="/">
            <i class="material-icons">whatshot</i>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon"></span>
            <span class="navbar-toggler-icon"></span>
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to 'Projects', projects_path, class: 'nav-link', style: 'padding-bottom: 10px' %>
            </li>
            <%= render 'layouts/partials/alerts' %>
          </ul>
          <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
              <li class="nav-item">
                <%= current_user.user_name %>
              </li>
              <li class="nav-item">
                <%= link_to("<i class='material-icons'>login</i> Logout".html_safe, "/logout", method: :delete, class: "nav-link", style: "padding-bottom: 10px") %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to("<i class='material-icons'>login</i> Login".html_safe, "/auth/google_oauth2", class: "nav-link", style: "padding-bottom: 10px") %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if controller_name == 'web_app' && action_name == 'landing' %>
    <div class="page-header header-filter" data-parallax="true" style="background-image: url(<%= asset_path 'dr2.jpg' %>)">
      <div class="container">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <div class="brand text-center">
              <h1>it's time to fight back</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
    <% else %>
      <div class="page-header header-filter" data-parallax="true" style="height: <%= @vh ? @vh : 50 %>vh; background-image: url(<%= @cover_img %>)">
      </div>
    <% end %>

    <%= yield %>
    <% unless controller_name == 'projects' && ['index','new'].include?(action_name) %>
      <%= render(CardsContainerComponent.new(title: "Find a#{controller_name == 'projects' && action_name == 'show' ? 'nother' : ''} project to support")) do %>
        <div class="row">
          <% Project.all.each do |project| %>
            <div class="col-12 col-md-6 col-xl-4">
              <%= render(ProjectCardComponent.new(project: project)) %>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>

    <footer class="footer footer-default" >
      <div class="container">
        <nav class="float-left">
          <ul>
            <li>
              <!-- <a href="">
              </a> -->
            </li>
          </ul>
        </nav>
        <div class="copyright float-right">
            <span id='year'></span>
            &copy;
            FightBack
            <script>
                $('#year').html(new Date().getFullYear())
            </script>
        </div>
      </div>
    </footer>
    <% console if Rails.env == "development" %>
  </body>
</html>

app/views/layouts/partials/_alerts.html.erb
<% if notice or alert %>
	<div class='alert alert-<%= notice ? 'info' : 'warning' %>'>
		<%= notice ? notice : alert %>
		<button class='close' role='button' data-dismiss='alert'>&times;</button>
	</div>
<% elsif flash[:notice] or flash[:alert] %>
	<div class='alert alert-<%= flash[:notice] ? 'info' : 'warning' %>'>
		<%= notice ? notice : alert %>
		<button class='close' role='button' data-dismiss='alert'>&times;</button>
	</div>
<% end %>

app/views/projects/_form.html.erb
<div data-controller="projects">
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :beneficiary %>
    <%= form.text_field :beneficiary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :goal_amount %>
    <%= form.text_field :goal_amount, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :goal_deadline %>
    <%= form.date_select :goal_deadline, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :project_status %>
    <%= form.select :project_status, options_for_select({"Active":"active","Complete":"complete","On Hold":"onhold"},"active"), {}, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: "btn btn-info" %>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<div class="main main-raised" style="margin: 0 30px 0 30px">
  <div class="section" style="padding-top: 0px">
    <div class="container">
      <div class="title">
        <div class="row">
          <div class="col-6"><h2 class="title" style="margin-bottom:0px;">New Project</h2></div>
          <div class="col-6 d-flex justify-content-end align-items-end">
            <%= link_to 'Back', projects_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="main main-raised" style="margin: 0 30px 0 30px">
  <div class="section" style="padding-top: 0px">
    <div class="container">
      <div class="title">
        <div class="row">
          <div class="col-6"><h2 class="title" style="margin-bottom:0px;">Projects</h2></div>
          <div class="col-6 d-flex justify-content-end align-items-end">
            <%= link_to 'New Project', new_project_path, class: 'btn btn-info' %>
          </div>
        </div>
      </div>
      <%= render 'layouts/partials/alerts' %>
      <%= render(BootstrapTableComponent.new(
        pagination: true,
        search: true,
        model: 'project',
        headers: [
          {sortable: 'true', field: 'name', title: 'Name'},
          {sortable: 'true', field: 'beneficiary', title: 'Beneficiary'},
          {sortable: 'true', field: 'goal_amount', title: 'Amount'},
          {sortable: 'true', field: 'goal_deadline', title: 'Deadline'},
          {sortable: 'true', field: 'project_status', title: 'Status'},
          {field: 'action_links', title: 'Actions'}
        ],
        data: @projects.order(created_at: :desc)
      ))%>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="main main-raised" style="margin: 0 30px 0 30px">
  <div class="section" style="padding-top: 0px">
    <div class="container">
      <div class="title">
        <div class="row">
          <div class="col-6"><h2 class="title" style="margin-bottom:0px;">New Project</h2></div>
          <div class="col-6 d-flex justify-content-end align-items-end">
            <%= link_to 'Back', projects_path, class: 'btn btn-default' %>
          </div>
        </div>
      </div>
      <%= render 'form', project: @project %>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div data-controller="donations">
  <div class="main main-raised" style="margin: 0 30px 0 30px">
    <div class="section" style="padding-top: 35px">
      <div class="container">
        <%= render 'layouts/partials/alerts' %>
        <%= render(ProjectDescriptionComponent.new(project: @project)) %>
        <div data-target="donations.progressBar">
          <%= render(ProgressBarComponent.new(goal: @project.goal_amount, current_amount: @project.donations.sum(:amount).to_f)) %>
        </div>
        <button type="button" class="btn btn-info float-right" data-toggle="modal" data-target="#donateModal">
        FightBack!
        </button>
        <h3><strong>Last donations</strong></h3>
          <div data-target="donations.table">
            <%= render(SimpleTableComponent.new(
              headers: ['Donator', 'Amount', 'Time'],
              data: @project.donations.includes(:user).order(created_at: :desc).limit(5).map{|d| 
                {
                  "Donator" => d.user ? d.user.user_name : 'Anonymous',
                  "Amount" => d.amount.to_i,
                  "Time" => d.created_at.to_formatted_s(:long_ordinal)
                }
              }
            ))%>
          </div>
      </div>
    </div>
    <div class="section" style="padding-top: 35px">
      <div class="container">
        <% if @project.images.attached? %>
          <%= render(ImagesCarouselComponent.new(images: @project.images)) %>
        <% end %>
      </div>
    </div>
  </div>
  <%= render(ModalComponent.new(
    title: "Are you ready to make a change?",
    modal_id: "donateModal",
    confirm_button_text: "Donate",
    confirm_data_action: "donations#addDonation",
    confirm_button_id: "donate-btn",
    body_message: "Donate to #{@project.beneficiary}"
  )) do %>
    <div class="d-none">
      <input data-target="donations.projectId" type="number" value="<%= @project.id %>" required>
    </div>
    <div class="form-group">
      <label for="payment-method">Payment Method</label>
      <select data-target="donations.paymentMethod" class="form-control" id="payment-method" aria-describedby="payment-method-help" required>
      <option value="" disabled selected>Select your option</option>
      <option value="paypal">PayPal</option>
      <option value="credit_card">Credit Card</option>
    </select>
      <small id="payment-method-help" class="form-text text-muted">We are working to integrate more payment methods in the near future.</small>
    </div>
    <div class="form-group">
      <label for="amount">Amount (USD)</label>
      <input data-target="donations.amount" type="number" min="1" step="any" value= 10 class="form-control" id="amount" placeholder="10" required>
    </div>
  <% end %>
</div>

app/views/web_app/landing.html.erb
<div class="main main-raised" style="margin: 0 30px 0 30px">
  <div class="section" style="padding-top: 35px">
    <div class="container">
      <div class="title">
        <h2 class="title">2020</h2>
      </div>
      <h4>It hasn't been a good year at all. COVID-19 has taken so many lifes away with so many governments in Latin America not taking enough actions to protect their people at least until a vaccine is developed. But now is time to fight back this disease, and it always comes down to us, the normal people, to stand up for ourselves.</h4>
      <h4>The first goal of <strong>&copy;fightback</strong> is to support projects that will protect our health professionals. The lack of supplies like N95 masks, gloves, face shields, respirators, disposable aprons or even just soap has resulted in thousands of health professionals dying because of this disease in Latin America. <strong>Health professionals are our first line of defense. If governments are not willing to protect them, then we will.</strong> This platform will allow you to donate to one of many projects that aim to fightback this and other diseases.</h4>
      <h4>Be part of this movement and <strong>prove that humanity deserves another chance.</strong></h4>
    </div>
  </div>
  <div class="section" style="padding-top: 35px">
    <div class="container">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/AH3Z0WP5g3I?controls=0" frameborder="0" allow="autoplay; modestbranding; accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <!--https://www.youtube.com/embed/Y1g6oKP2-vU-->
        <!--https://www.youtube.com/embed/mg3Us2cYXq8-->
      </div>
    </div>
  </div>
</div>